<?xml version="1.0" standalone="yes"?>
<!DOCTYPE students [
<!ELEMENT students (student)+>
<!ELEMENT student (firstName, lastName, email, university)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT university (name, faculty, major)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT faculty (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ATTLIST student 
    studentId CDATA #REQUIRED
    gender CDATA #IMPLIED>
]>

<students> 
    <student studentId="66130500059" gender="Male">
        <firstName>Pawarit</firstName>
        <lastName>Samriang</lastName>
        <email>pawarit.samriang@gmail.com</email>
        <university> 
            <name>King Mongkut's University of Technology Thonburi</name>
            <faculty>Information Technology</faculty>
            <major>Information Technology</major>
        </university>
    </student>
</students>

